### ISSUE TITLE
Site nav updates

### ISSUE THREAD

**Issue by thinq4yourself** [BeardandFedora/writeon.io#9]
Need to add some updates to the nav, either text or icons or both:
- [Blog](http://blog.writeon.io)
- [Community](https://writeon.uservoice.com)
- [Twitter](https://twitter.com/WriteOnApp)
- [Facebook](https://www.facebook.com/writeon.io)
- [Support](support@writeon.io)

**Comment by yaboi** [comment]
My vote is to add most of these to the footer nav, next to Privacy Policy.

For the purposes of on boarding, especially at this stage, I like the idea of keeping the "above the fold" strictly focused on "signing up" and "getting started." If they get to the homepage, they most likely have the intent of signing up or already know about WriteOn. Brand awareness (e.g. Blog, Community, Social, etc.) should already be established.

If they want to "learn more" they will most likely scroll through the page, landing at the bottom. After a second CTA to Sign Up, they can then explore the blog, community, socials. With that being said, the only other link listed above, and besides "Features", I think would fit in the top nav is "Community" since it might have a similar affect as "Features."

#MyTwoCents #OnlyWorthAPenny #YourTheOtherPenny

@thinq4yourself, thoughts?

**Comment by yaboi** [comment]
I'd like to revisit how much is loaded into the top nav bar. Nine links, four of which lead off-site, might be a little much for top level importance.

Maybe we should create some user funnels, then design the navigation links around the funnels. What is needed there to answer questions that will lead to our users through the right funnels.

thoughts @thinq4yourself ?

**Comment by thinq4yourself** [comment]
I'm taking all this info, plus other new issues, into account over the weekend. Some is consistent with logic, some needs more insight and data. We have reached to level I will require data or hard proven experience to make major changes. What we had before was not working, or going to work, so as we move forward let's keep this type of dialog about us. Standup on Monday?
